"""
AstroLive Retention Engine — synthetic data generator.

Generates astrologers, users, and a consultation history timeline with a
hidden 'engagement type' per user that drives realistic, noisy behavioral
patterns (frequency, recency, spend trend, ratings, failed calls).

Design notes:
- Each user has a latent engagement_type (one_time / occasional / loyal)
  that sets a base consultation cadence, but individual behavior has
  randomness layered on top (drift, random reactivation, random drop-off)
  so the resulting patterns are correlated with but not deterministic
  from the labels used downstream. This keeps the churn-prediction task
  non-trivial instead of a lookup table.
"""
import numpy as np
import pandas as pd
import json
from datetime import datetime, timedelta

RNG = np.random.default_rng(42)
TODAY = datetime(2026, 8, 15)

# ---------------------------------------------------------------------------
# Astrologers
# ---------------------------------------------------------------------------
SPECIALIZATIONS = ["Career", "Relationship", "Marriage", "Finance", "Family", "Health", "General Vedic"]
FIRST_NAMES = ["Rahul", "Priya", "Anjali", "Vikram", "Sunita", "Deepak", "Meera", "Arjun", "Kavita", "Rohan",
               "Neha", "Sanjay", "Pooja", "Amit", "Divya", "Karan", "Ritu", "Manoj", "Shreya", "Ashok",
               "Nisha", "Rajesh", "Swati", "Vivek", "Anita", "Suresh", "Preeti", "Gopal", "Lata", "Harish"]

N_ASTROLOGERS = 30
astrologers = []
for i in range(N_ASTROLOGERS):
    experience = int(RNG.integers(1, 25))
    base_skill = np.clip(RNG.normal(0.72, 0.12), 0.35, 0.98)  # drives rating quality
    astrologers.append({
        "astrologer_id": f"A{i+1:03d}",
        "name": FIRST_NAMES[i % len(FIRST_NAMES)],
        "specialization": RNG.choice(SPECIALIZATIONS, p=[0.22, 0.20, 0.12, 0.14, 0.10, 0.10, 0.12]),
        "experience_years": experience,
        "price_per_min": int(RNG.choice([9, 12, 15, 18, 22, 25, 30])),
        "base_skill": round(float(base_skill), 3),
    })
astrologers_df = pd.DataFrame(astrologers)

# ---------------------------------------------------------------------------
# Users + engagement type
# ---------------------------------------------------------------------------
N_USERS = 900
ENGAGEMENT_TYPES = ["one_time", "occasional", "loyal"]
ENGAGEMENT_P = [0.42, 0.36, 0.22]

# type -> (mean gap between consultations in days, gap std, base engagement score)
TYPE_PARAMS = {
    "one_time":   {"gap_mean": 400, "gap_std": 120, "engagement_base": 0.20},
    "occasional": {"gap_mean": 55,  "gap_std": 25,  "engagement_base": 0.50},
    "loyal":      {"gap_mean": 20,  "gap_std": 10,  "engagement_base": 0.80},
}

USER_NAME_POOL = [f"User{i+1000}" for i in range(N_USERS)]

users = []
for uid in range(N_USERS):
    etype = RNG.choice(ENGAGEMENT_TYPES, p=ENGAGEMENT_P)
    signup_days_ago = int(RNG.integers(60, 400))  # signed up 60-400 days before TODAY
    signup_date = TODAY - timedelta(days=signup_days_ago)
    # per-user noise multiplier on top of type base (individual variation)
    drift = float(np.clip(RNG.normal(1.0, 0.35), 0.3, 2.2))
    free_trial_used = True  # every user gets the free first consultation
    converted_to_paid = bool(RNG.random() < (0.35 if etype == "one_time" else 0.75 if etype == "occasional" else 0.93))
    users.append({
        "user_id": f"U{uid+1:04d}",
        "name": USER_NAME_POOL[uid],
        "signup_date": signup_date,
        "engagement_type": etype,   # hidden ground-truth type, NOT exposed as a feature
        "drift": drift,
        "converted_to_paid": converted_to_paid,
        "preferred_topic": RNG.choice(SPECIALIZATIONS, p=[0.22, 0.20, 0.12, 0.14, 0.10, 0.10, 0.12]),
    })
users_df = pd.DataFrame(users)

# ---------------------------------------------------------------------------
# Consultation timeline simulation
# ---------------------------------------------------------------------------
consultations = []
consult_id = 1

for _, u in users_df.iterrows():
    etype = u["engagement_type"]
    params = TYPE_PARAMS[etype]
    signup = u["signup_date"]
    days_available = (TODAY - signup).days

    if not u["converted_to_paid"] and etype == "one_time":
        # took the free consult and never came back at all
        n_events = 1
    else:
        n_events = None  # generated by gap process below

    t = 0  # days since signup
    events = []
    # first consultation is always shortly after signup (the free trial / first booking)
    first_gap = int(max(0, RNG.normal(3, 3)))
    t += first_gap
    preferred_astrologer = None
    if t <= days_available:
        events.append(t)

    if n_events != 1:
        while True:
            mean_gap = params["gap_mean"] / u["drift"]
            # occasional random re-engagement burst or random long silence
            if RNG.random() < 0.08:
                mean_gap *= RNG.choice([0.3, 2.5])  # burst or extra silence
            gap = max(1, RNG.normal(mean_gap, params["gap_std"]))
            t += gap
            if t > days_available:
                break
            events.append(t)
            # loyal/occasional users occasionally stop early (organic churn even if "type" says loyal)
            if RNG.random() < 0.015:
                break

    if not events:
        continue

    # pick a preferred astrologer for this user (70% of repeat visits go to them)
    pref_astro = astrologers_df.sample(1, random_state=int(RNG.integers(0, 1_000_000))).iloc[0]

    for idx, day_offset in enumerate(events):
        c_date = signup + timedelta(days=float(day_offset))
        if c_date > TODAY:
            continue
        use_preferred = RNG.random() < 0.70 and idx > 0
        astro = pref_astro if use_preferred else astrologers_df.sample(1, random_state=int(RNG.integers(0, 1_000_000))).iloc[0]

        topic = u["preferred_topic"] if RNG.random() < 0.6 else RNG.choice(SPECIALIZATIONS)
        mode = RNG.choice(["chat", "audio", "video"], p=[0.5, 0.35, 0.15])
        duration = max(3, int(RNG.normal(12 if mode != "chat" else 8, 5)))
        # spend trend: loyal users' spend per session creeps up slightly over time; one-time is just the free trial
        session_num_factor = 1 + 0.02 * idx
        amount = 0 if idx == 0 else round(duration * astro["price_per_min"] * session_num_factor, 0)

        call_status = "completed" if RNG.random() > 0.05 else RNG.choice(["failed", "dropped"])
        rating_given = None
        if call_status == "completed":
            rating_given = int(np.clip(round(RNG.normal(astro["base_skill"] * 5, 0.6)), 1, 5))

        consultations.append({
            "consultation_id": f"C{consult_id:06d}",
            "user_id": u["user_id"],
            "astrologer_id": astro["astrologer_id"],
            "date": c_date,
            "topic": topic,
            "mode": mode,
            "duration_min": duration,
            "amount": amount,
            "call_status": call_status,
            "rating_given": rating_given,
            "is_free_trial": idx == 0,
        })
        consult_id += 1

consultations_df = pd.DataFrame(consultations)

# ---------------------------------------------------------------------------
# Save
# ---------------------------------------------------------------------------
astrologers_df.to_csv("/root/astrolive/data/astrologers.csv", index=False)
users_df.drop(columns=["drift"]).to_csv("/root/astrolive/data/users.csv", index=False)
consultations_df.to_csv("/root/astrolive/data/consultations.csv", index=False)

print(f"Astrologers: {len(astrologers_df)}")
print(f"Users: {len(users_df)}")
print(f"Consultations: {len(consultations_df)}")
print(f"Users with >=1 consultation: {consultations_df['user_id'].nunique()}")
print(consultations_df.groupby(users_df.set_index('user_id').loc[consultations_df['user_id'], 'engagement_type'].values).size())
